### PR TITLE
use querystring from original path upon loading the page

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
@chessai `nix-build` cannot actually build this correctly because jsaddle-warp is being a curmudgeon about the version of http-types. However, I'm able use this correctly in allsight, so I think everything's alright.

**Comment by andrewthad** [comment]
This doesn't actually appear to produce the desired result though. I'll give it another try.

**Comment by chessai** [comment]
Just seeing this, @andrewthad, sorry. With what does jsaddle-warp complain, exactly?

**Comment by andrewthad** [comment]
Here is the relevant part of the log:

```
unpacking source archive /nix/store/hp45vb5wsrndiymjc91g9p4xnr1hfkd8-jsaddle-warp
source root is jsaddle-warp
/nix/store/j1ly0zzpnzb8y8ry6k4vi4prk8vwq233-set-source-date-epoch-to-latest.sh: line 7: warning: command substitution: ignored null byte in input
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-jsaddle-warp-0.9.4.0.drv-0/package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-jsaddle-warp-0.9.4.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/xib3ndqfi3zl9w0fywb9w1j19sh2d23p-jsaddle-warp-0.9.4.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/8df5zf660wj7jxyv3w0wn323zl55xz8g-jsaddle-warp-0.9.4.0-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-jsaddle-warp-0.9.4.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/xib3ndqfi3zl9w0fywb9w1j19sh2d23p-jsaddle-warp-0.9.4.0/lib/ghc-8.2.1/jsaddle-warp-0.9.4.0 --ghc-option=-j4 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --ghc-option=-split-sections --ghc-options=-fexpose-all-unfoldings --extra-lib-dirs=/nix/store/sldddw66nndddmjf6knlla50ls5dkkxf-ncurses-6.0-20170902/lib --extra-lib-dirs=/nix/store/h9g62cvpviyhfp3v5k6qwb7k2pafg23a-gmp-6.1.2/lib
Configuring jsaddle-warp-0.9.5.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:948:20 in Cabal-2.0.0.2:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:470:12 in Cabal-2.0.0.2:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:570:20 in Cabal-2.0.0.2:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.0.0.2:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:174:19 in Cabal-2.0.0.2:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:119:27 in Cabal-2.0.0.2:Distribution.Simple
  defaultMain, called at Setup.lhs:5:10 in main:Main
Setup: Encountered missing dependencies:
http-types >=0.8.6 && <0.10
builder for ‘/nix/store/kjj6j4g6ynxncqbadjf2g2n4mp4pv448-jsaddle-warp-0.9.4.0.drv’ failed with exit code 1
```

**Comment by andrewthad** [comment]
Also, that error happens on both my work laptop and my personal laptop.

**Comment by chessai** [comment]
This looks like it is simply because we are not overriding jsaddle-warp with a version that accepts the newest http-types. I am about to push a change which fixes this.

**Comment by chessai** [comment]
I pushed the change.

**Comment by chessai** [comment]
@andrewthad did this work?

**Comment by andrewthad** [comment]
it did

**Pull request merged**
